
The following have been reloaded with a version change:
  1) devel/cuda/12.2 => devel/cuda/12.4

2025-01-30 01:21:51.805974: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-30 01:21:51.818403: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738196511.830595 3442747 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738196511.834270 3442747 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-30 01:21:51.848626: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:root:Starting parallel dataset generation...
Traceback (most recent call last):
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 274, in <module>
    scenarios_generate(n_list, distribution_list, SNR_list, grid_size, alpha_l, beta_nl, n_rep=1, n_cores=n_core,
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 226, in scenarios_generate
    with mp.Pool(n_cores) as pool:
  File "/usr/lib64/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 204, in __init__
    if processes < 1:
TypeError: '<' not supported between instances of 'Pool' and 'int'
Exception ignored in: <function Pool.__del__ at 0x15376174a0d0>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 268, in __del__
  File "/usr/lib64/python3.9/multiprocessing/queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
cp: cannot stat '/scratch/slurm_tmpdir/job_1495807/output': No such file or directory
